# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

- name: This playbook ensures that dotnet sdk has been installed
  hosts: homelab_server

  vars_files:
    - vars/settings.yaml
    
  tasks:

    - name: Homelab server - dotnet sdk installation -- configure repo under CentoS
      block:
        - name: Homelab server - dotnet sdk installation -- install repo under CentOS
          shell:
            cmd:          "rpm --force -Uvh https://packages.microsoft.com/config/centos/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm"
            warn:         false
          become:         true

        - name: Homelab server - dotnet sdk installation -- refresh yum cache
          yum:
            update_cache: yes
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 3.1
          yum:
            name:         dotnet-sdk-3.1
            state:        latest
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 5.0
          yum:
            name:         dotnet-sdk-5.0
            state:        latest
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 6.0
          yum:
            name:         dotnet-sdk-6.0
            state:        latest
          become:         true

      when: ansible_distribution == 'CentOS'

    - name: Homelab server - dotnet sdk installation -- configure repo under Ubuntu
      block:
        - name: Homelab server - dotnet sdk installation -- retreive .deb under Ubuntu
          get_url:
            url:          "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
            dest:         "/tmp/packages-microsoft-prod.deb"

        - name: Homelab server - dotnet sdk installation -- install .deb under Ubuntu
          shell:
            cmd:          "dpkg -i /tmp/packages-microsoft-prod.deb"
          become:         true

        - name: Homelab server - dotnet sdk installation -- refresh apt cache
          shell:
            cmd:          apt update
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 3.1
          apt:
            name:         dotnet-sdk-3.1
            state:        latest
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 5.0
          apt:
            name:         dotnet-sdk-5.0
            state:        latest
          become:         true

        - name: Homelab server - dotnet sdk installation -- install/upgrade the dotnet sdk 6.0
          apt:
            name:         dotnet-sdk-6.0
            state:        latest
          become:         true

      when: ansible_distribution == 'Ubuntu'
